name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok
      run: |
        curl -shttps://bin.equinox.io/c/b3M412wjq1U/ngrok-v3-stable-windows-amd64.zip -o ngrok.zip
        tar -xf ngrok.zip
    - name: Authenticate Ngrok
      run: .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Create RDP User
      run: |
        net user runneradmin Password12345! /add
        net localgroup administrators runneradmin /add
    - name: Start Tunnel
      run: Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389"
    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
